name: Build and publish a Docker image to ghcr.io
on:
  workflow_dispatch:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - master

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}

        
      - name: 'Portainer Deploy'
        uses: cssnr/portainer-stack-deploy-action@v1
        with:
            token: ${{ secrets.PORTAINER_TOKEN }}
            url: ${{ secrets.PORTAINER_HOST }}
            name: subvpn-bot
            file: docker-compose.yaml
            standalone: true
            env_json: '{"LOG_LEVEL": "INFO","BOT_TOKEN": "${{secrets.BOT_TOKEN}}","CHECK_COOLDOWN": "10","PANEL_ADDRESS":"${{secrets.PANEL_ADDRESS}}","PANEL_PASS":"${{secrets.PANEL_PASS}}","PANEL_USERNAME":"${{secrets.PANEL_USERNAME}}","TARGET_CHANNEL":"${{secrets.TARGET_CHANNEL}}"}'
             
